### ISSUE TITLE
customize wisp

### ISSUE THREAD

**Issue by NA3** [jadissa/watchchat#1]
hi, 
is it possible to customise the wisp to can click on the name of the user for wisp it directly?

**Comment by jadissa** [comment]
thanks for the inquiry.
this has been solved in the most recent commit and has been published out to curseforge
https://github.com/jadissa/watchchat/blob/master/ui.lua#L216

**Comment by NA3** [comment]
it no wisp anymore, with prat and wim
can you maque it don't watch when it's me was spaming?

**Comment by jadissa** [comment]
> it no wisp anymore, with prat and wim
whispers were removed. inline messages are now delivered instead and those are prefixed with wc

> can you make it don't watch when it's me was spaming?
i intentionally added this so that users could test. i'll look at removing it in a future release

**Comment by NA3** [comment]
can you tell me how to add wisp please?

**Comment by jadissa** [comment]
>can you make it don't watch when it's me was spaming?

this was handled in the following commit
https://github.com/jadissa/watchchat/commit/97e98f8cf35f8526e7e8850756f972ba92cfb160

>can you tell me how to add wisp please?

you are welcome to fork the project but for now, whispering has been removed from the addon, in preference for inline notifications
