### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SegoItCh** [jadissa/watchchat#2]
Message: Interface\AddOns\watchchat\ui.lua:105: attempt to concatenate local 'input' (a nil value)
Time: Sat Aug 22 15:21:09 2020
Count: 1
Stack: Interface\AddOns\watchchat\ui.lua:105: attempt to concatenate local 'input' (a nil value)
...ddOns\adblock\Libs\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
Interface\FrameXML\ChatFrame.lua:4695: in function <Interface\FrameXML\ChatFrame.lua:4642>
[C]: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4356: in function <Interface\FrameXML\ChatFrame.lua:4355>
[C]: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4392: in function <Interface\FrameXML\ChatFrame.lua:4388>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: input = "watch"
editBox = ChatFrame1EditBox {
 0 = <userdata>
 customAutoCompleteFunction = <function> defined @Interface\FrameXML\ChatFrame.lua:3903
 command = "/wc"
 SetBackdropBorderColor = <function> defined =[C]:-1
 language = "Common"
 template = "Default"
 text = "/"
 autoCompleteXOffset = 35
 hookedByAceTab3 = true
 history_index = 0
 history_lines = <table> {
 }
 glossTex = true
 characterCount = <unnamed> {
 }
 tabCompleteTableIndex = 1
 at3matches = <table> {
 }
 PixelSnapDisabled = true
 setText = 0
 chatFrame = ChatFrame1 {
 }
 addSpaceToAutoComplete = true
 historyLines = <table> {
 }
 lDrag = <unnamed> {
 }
 historyIndex = 0
 AddHistoryLine = <function> defined =[C]:-1
 at3curMatch = 0
 autoCompleteParams = <table> {
 }
 headerSuffix = ChatFrame1EditBoxHeaderSuffix {
 }
 ClearHistory = <function> defined =[C]:-1
 languageID = 7
 chatStyle = "classic"
 header = ChatFrame1EditBoxHeader {
 }
 addHighlightedText = true
 rDrag = <unnamed> {
 }
 frame = <unnamed> {
 }
 pixelBorders = <table> {
 }
 SetBackdropColor = <function> defined =[C]:-1
}
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\adblock\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\adblock\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\adblock\Libs\AceConsole-3.0\AceConsole-3.0.lua:85
 EnableModule = <function> defined @Interface\AddOns\adblock\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\adblock\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\adblock\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 list = <function> defined @Interface\AddOns\watchchat\ui.lua:165
 defaultModuleLibraries = <table> {
 }
 sound = <function> defined @Interface\AddOns\watchchat\ui.lua:179
 UnregisterChatCommand = <function> defined @Interface\AddOns\adblock\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 options = <table> {
 }
 init = <function> defined @Interface\AddOns\watchchat\ui.lua:13
 Printf = <function> defined @Interface\AddOns\adblock\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 unwatch = <function> defined @Interface\AddOns\watchchat\ui.lua:115
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\adblock\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 ignore = <function> defined @Interface\AddOns\watchchat\ui.lua:129
 persistence = <table> {
 }
 name = "wc_ui"
 IsEnabled = <function> defined @Interface\AddOns\adblock\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\adblock\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 limit = 20
 color = <function> defined @Interface\AddOns\watchchat\ui.lua:77
 notify = <function> defined @Interface\AddOns\watchchat\ui.lua:209
 processInput = <function> defined @Interface\AddOns\watchchat\ui.lua:46
 GetArgs = <function> defined @Interface\AddOns\adblock\Libs\AceConsole-3.0\AceConsole-3.0.lua:144
 Print = <function> defined @Interface\AddOns\adblock\Libs\AceConsole-3.0\AceConsole-3.0.lua:54
 ignores = <table> {
 }
 watches = <table> {
 }
 channels = <table> {
 }
 help

**Comment by jadissa** [comment]
I started addressing this issue here: https://www.curseforge.com/wow/addons/watchchat?comment=5
will follow up in this thread however

**Comment by jadissa** [comment]
This issue was fixed in a previous release. Closing this out. Ty for the report
